### ISSUE TITLE
Fullcalendar: Allow switching between different calendar views

### ISSUE THREAD

**Issue by susruthi-k** [Husky-Coding-Project/calendar#7]
SKILLS: essentially copying and pasting code. But you’ll have to look at different documentation to combine the right code together. Essential skill: looking at developer console for error messages. It *would* help if you knew about importing/exporting, classes, objects, functions, etc. 

TIME REQUIRED: 1.5 hours at most, most likely 30 minutes

NUMBER OF PEOPLE: 1 person

**Comment by emilykangdev** [comment]
If you just load `main-with-script` (this is the html file with JS code inside it), you can see that there's already different views in the options. New time estimation for adding the daily view is about 5-10m max. 

But reading the docs around this would take longer. And #10 is just about putting all that code into an external js file, so the options themselves don't change.

**Comment by emilykangdev** [comment]
Fixed with one line of code :)

`headerToolbar: { center: 'dayGridMonth,timeGridWeek' },`
