### ISSUE TITLE
Fullcalendar: Test of daily, monthly, and weekly views

### ISSUE THREAD

**Issue by jc0112** [Husky-Coding-Project/calendar#8]
What the team member needs to complete:
- Make the views to show up in three different HTML files in the browser.

The skills required to complete the task:
- Copy and paste codes
- read and follow the documentations
- debug with browser console
- HTML

Estimated difficulty of the task:
- Medium, not too hard

Estimated time required to complete the task.
- at most 2 hours
- expecting around 1 hour

**Comment by emilykangdev** [comment]
Well the documentation is easy to follow and adding the monthly and weekly views was like 4 lines. The next issue is about allowing the user to create events / select days/time slots in the monthly/weekly views. #12 

Also the weekly view IS the daily view x 7.
